version: '3'
services:
  gateway:
    container_name: burning-gateway
    build: ./api
    ports: 
      - 8081:8081
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    networks:
      - burning-network
      
  # Vue App
  client:
    container_name: burning-client
    build: ./client
    ports:
      - 8080:80

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      # - ./burning-nginx/error.log:/var/log/nginx/error.log
      # - ./burning-nginx/cache:/etc/nginx/cache
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - gateway
      - client
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

# Networks to be created to facilitate communication between containers
networks:
  burning-network:
    driver: bridge

volumes:
  api:
