version: "3"

services:

  # Nginx reverse proxy
  burning-nginx:
    image: nginx:latest
    depends_on: 
      - burning-client
      - burning-web-api
    volumes:
      - ./burning-nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./burning-nginx/error.log:/var/log/nginx/error.log
      - ./burning-nginx/cache:/etc/nginx/cache
    ports:
      - 80:80
      - 443:443
    restart: always

  # Vue App
  burning-client:
    image: burning-client
    build:
      context: ./burning-client
    ports:
      - 8080:80

  # Web Api
  burning-web-api:
    image: burning-web-api
    build: 
      context: burning-web-api
    depends_on:
      - burning-database
    env_file:
      - ./burning-web-api/.env.production
    ports:
      - 8081:8081
    # command: bash -c "./wait-for-ut.sh burning-database:27017 -- sh start.sh"


  # MongoDB
  burning-database:
    image: mongo
    env_file:
      - ./burning-database/vars.env
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./burning-database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./burning-database:/data/db

volumes:
  burning-database: