version: '3'
services:
  app:
    container_name: burning_app
    build: ./api
    ports: 
      - 8081:8081
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - burning-postgres
    networks:
      - burning-network
      
  # Vue App
  client:
    container_name: burning_client
    build: ./client
    ports:
      - 8080:80

  burning-postgres:
    image: postgres:latest
    container_name: burning_db
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - burning_db:/var/lib/postgresql/data
    networks:
      - burning-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./burning-nginx/error.log:/var/log/nginx/error.log
    #   - ./burning-nginx/cache:/etc/nginx/cache
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - client
    restart: always

volumes:
  api:
  burning_db:

# Networks to be created to facilitate communication between containers
networks:
  burning-network:
    driver: bridge
