version: '3'

services:
  app_test:
    container_name: burning_app_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - api_tests:/app/src/app/
    depends_on:
      - burning-postgres-test
    networks:
      - burning-network-test

  burning-postgres-test:
    image: postgres:latest
    container_name: burning_db_test
    environment:
      - POSTGRES_USER=${TEST_DB_USER}  
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
      - DATABASE_HOST=${TEST_DB_HOST} 
    ports:
      - '5555:5432'
    volumes:
      - burning_db_test:/var/lib/postgresql/data
    networks:
      - burning-network-test
  
volumes:
  api_tests:
  burning_db_test:

networks:
  burning-network-test:
    driver: bridge